### ISSUE TITLE
Changing default database location

### ISSUE THREAD

**Issue by ivon852** [flathub/io.github.hydrusnetwork.hydrus#15]
Hello, it is possible to change the database location of the Flatpak build?

The default database location of Flatpak build is located at`~/Hydrus`. Shouldn't it be located at `~/var/io.github.hydrusnetwork.hydrus` instead?

Or the database should be placed in `/home/user/.local/share/hydrus/` as the [AUR](https://aur.archlinux.org/packages/hydrus) version did. Thanks.

**Comment by bbhtt** [comment]
Did you try the Readme https://github.com/flathub/io.github.hydrusnetwork.hydrus#pass-arguments-eg-change-database-location

> shouldn't it be located at ~/var/io.github.hydrusnetwork.hydrus instead?

It should but they don't seem to do that.

**Comment by ivon852** [comment]
> Did you try the Readme https://github.com/flathub/io.github.hydrusnetwork.hydrus#pass-arguments-eg-change-database-location ?
> 
Oh I see. I am on Arch Linux. Now it works. Thank you very much!

**Comment by Chemrat** [comment]
Default location setting can be wrapped in .sh script that would also override entrypoint, i.e. `hydrus.sh`:
```bash
#!/bin/sh

/app/hydrus_client.py --db_dir ~/.var/app/$FLATPAK_ID/data
```
and
```yaml
    build-commands:
      - install -D hydrus.sh /app/bin/org.hydrusnetwork.Hydrus
```

There's also no reason why Hydrus should have `--filesystem=home` by default, especially if defaults will reside in writeable directory.
This however will mess with existing setups (people will need to manually move their DB and set up folder access). Thoughts?

**Comment by bbhtt** [comment]
Isn't home required to load images and videos too? You can just revoke `--filesystem=home` and add `--filesystem=~/Hydrus:create` too.

**Comment by Chemrat** [comment]
1. Client files location defaults to `client_files` folder in the DB path, so Hydrus will work fine with its own database.
2. Importing URLs, etc. will work fine since it doesn't rely on local disk access.
3. Unless Hydrus will make better use of portals (which it currently doesn't), importing files from local disk would require specific permissions. Without `--filesystem=home`, users will be **unable** to import from any paths outside of `~/.var/app/io.github.hydrusnetwork.hydrus/`. Neither Hydrus will be able to export anywhere outside of that folder.

This is a safer but more inconvinient default. But I feel like this goes in line with general idea of sandboxing apps.

**Comment by Chemrat** [comment]
Obviously, if users want to, they can re-add `--filesystem=home` through flatseal, opposite to revoking it after the install.

**Comment by bbhtt** [comment]
What happens with `--filesystem=~/Hydrus:create`? This would need no database migration and blocks access to `home`. Users can add more paths as they need.

If it works I'm fine with this change.

Database migration can be annoying, because I don't have a way to notify everyone and suddenly their apps break.

**Comment by Chemrat** [comment]
That should be a better default than `home`, though I haven't tested that.
Honestly for now I'll probably withdraw proposal of any changes.
1. I want to look at portal API and see if we can keep arbitrary path imports without giving full access.
2. I want to see if maybe more advanced wrapper script can use `~/Hydrus` if already exists or default to flatpak dir on a fresh install.
3. Maybe there's a non-annoying way to notify users about changes too, like a one-time dialogue popup before hydrus start.
